name: edgetpu-runtime

on:
  pull_request:
    paths-ignore:
        - '**/*.md'
        - 'LICENSE*'
  push:
    tags:
      - 'v*'
    branches:
      - master
      - test-*
    paths-ignore:
    - '**/*.md'
    - 'LICENSE*'

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: DOCKER_TARGETS=libedgetpu make docker-build

      - name: Release
        run: |
          export PACK_DIR=edgetpu_runtime

          export LIBEDGETPU_NAME=k8
          export TRIPLET=x86_64-linux-gnu
          bash scripts/pack.sh out "${LIBEDGETPU_NAME}" "${TRIPLET}" "${PACK_DIR}"
          export ZIP_FILENAME="edgetpu_runtime_${TRIPLET}_${GITHUB_REF##*/}"
          zip -r -9 -y "${ZIP_FILENAME}.zip" "${PACK_DIR}"
          rm -rf "${PACK_DIR}"

          export LIBEDGETPU_NAME=armv7a
          export TRIPLET=armv7l-linux-gnueabihf
          bash scripts/pack.sh out "${LIBEDGETPU_NAME}" "${TRIPLET}" "${PACK_DIR}"
          export ZIP_FILENAME="edgetpu_runtime_${TRIPLET}_${GITHUB_REF##*/}"
          zip -r -9 -y "${ZIP_FILENAME}.zip" "${PACK_DIR}"
          rm -rf "${PACK_DIR}"

          export LIBEDGETPU_NAME=aarch64
          export TRIPLET=aarch64-linux-gnu
          bash scripts/pack.sh out "${LIBEDGETPU_NAME}" "${TRIPLET}" "${PACK_DIR}"
          export ZIP_FILENAME="edgetpu_runtime_${TRIPLET}_${GITHUB_REF##*/}"
          zip -r -9 -y "${ZIP_FILENAME}.zip" "${PACK_DIR}"
          rm -rf "${PACK_DIR}"

          export LIBEDGETPU_NAME=riscv64
          export TRIPLET=riscv64-linux-gnu
          bash scripts/pack.sh out "${LIBEDGETPU_NAME}" "${TRIPLET}" "${PACK_DIR}"
          export ZIP_FILENAME="edgetpu_runtime_${TRIPLET}_${GITHUB_REF##*/}"
          zip -r -9 -y "${ZIP_FILENAME}.zip" "${PACK_DIR}"
          rm -rf "${PACK_DIR}"

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "edgetpu_runtime_*.zip"

  build_macos:
    runs-on: macos-11
    env:
      USE_BAZEL_VERSION: "5.4.0"
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install libusb
          pip3 install numpy

      - name: Compile
        run: |
          CPU=darwin_arm64 make
          CPU=darwin_x86_64 make

      - name: Release
        run: |
          export PACK_DIR=edgetpu_runtime

          export LIBEDGETPU_NAME=darwin_arm64
          export TRIPLET=aarch64-apple-darwin
          bash scripts/pack.sh out "${LIBEDGETPU_NAME}" "${TRIPLET}" "${PACK_DIR}"
          export ZIP_FILENAME="edgetpu_runtime_${TRIPLET}_${GITHUB_REF##*/}"
          zip -r -9 -y "${ZIP_FILENAME}.zip" "${PACK_DIR}"
          rm -rf "${PACK_DIR}"

          export LIBEDGETPU_NAME=darwin_x86_64
          export TRIPLET=x86_64-apple-darwin
          bash scripts/pack.sh out "${LIBEDGETPU_NAME}" "${TRIPLET}" "${PACK_DIR}"
          export ZIP_FILENAME="edgetpu_runtime_${TRIPLET}_${GITHUB_REF##*/}"
          zip -r -9 -y "${ZIP_FILENAME}.zip" "${PACK_DIR}"
          rm -rf "${PACK_DIR}"

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "edgetpu_runtime_*.zip"
