name: edgetpu-runtime-windows

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
        - '**/*.md'
        - 'LICENSE*'
  push:
    tags:
      - 'v*'
    branches:
      - master
      - test-*
    paths-ignore:
    - '**/*.md'
    - 'LICENSE*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: windows-2022
    env:
      USE_BAZEL_VERSION: "6.5.0"
      LIBUSB_VERSION: "1.0.27"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install six numpy wheel
          choco install -y 7zip
          mkdir -p /c/windows/temp
          curl -fSL "https://github.com/libusb/libusb/releases/download/v${LIBUSB_VERSION}/libusb-${LIBUSB_VERSION}.7z" -o /c/windows/temp/libusb-${LIBUSB_VERSION}.7z
          7z x -o/c/libusb /c/windows/temp/libusb-${LIBUSB_VERSION}.7z

      - name: Compile
        shell: bash
        run: |
          ./build.bat

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
