name: edgetpu-runtime-windows

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
        - '**/*.md'
        - 'LICENSE*'
  push:
    tags:
      - 'v*'
    branches:
      - master
      - test-*
    paths-ignore:
    - '**/*.md'
    - 'LICENSE*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: windows-2022
    env:
      USE_BAZEL_VERSION: "6.5.0"
      LIBUSB_VERSION: "1.0.27"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
